### ISSUE TITLE
go get fails for v2.28.0 with go1.25.4

### ISSUE THREAD

**Issue by geberl** [amacneil/dbmate#707]
**Description**

- Version: v2.28.0
- Database: -
- Operating System: go version go1.25.4 darwin/arm64

**Steps To Reproduce**

```
go mod init foo
go: creating new go.mod: module foo
go: to add module requirements and sums:
        go mod tidy

go get github.com/amacneil/dbmate/v2@v2.28.0
(... some downloads)
go: github.com/amacneil/dbmate/v2 imports
        github.com/amacneil/dbmate/v2/pkg/driver/postgres: cannot find module providing package github.com/amacneil/dbmate/v2/pkg/driver/postgres
(exit code 1)
```

I guess this has to do something with the MRs that make up v2.28.0, as the same works for v2.27.0.

Or with the latest go version 1.25.4, as this also works with 1.24.10 (with both 2.27.0 and 2.28.0)

```
go mod init foo
go: creating new go.mod: module foo
go: to add module requirements and sums:
        go mod tidy

go get github.com/amacneil/dbmate/v2@v2.27.0
(... some downloads)
(exit code 0)
```

**Expected Behavior**

The user should be able to go get v2.28.0 in go 1.25.4

**Comment by geberl** [comment]
Works again in go 1.25.5:

```
go mod init foo
go: creating new go.mod: module foo

go version
go version go1.25.5 darwin/arm64

go get github.com/amacneil/dbmate/v2@v2.28.0
go: added cloud.google.com/go v0.121.4
go: added cloud.google.com/go/auth v0.16.3
go: added cloud.google.com/go/auth/oauth2adapt v0.2.8
go: added cloud.google.com/go/bigquery v1.69.0
go: added cloud.google.com/go/compute/metadata v0.7.0
go: added cloud.google.com/go/iam v1.5.2
go: added filippo.io/edwards25519 v1.1.0
go: added github.com/ClickHouse/ch-go v0.67.0
go: added github.com/ClickHouse/clickhouse-go/v2 v2.39.0
go: added github.com/amacneil/dbmate/v2 v2.28.0
go: added github.com/andybalholm/brotli v1.2.0
go: added github.com/apache/arrow/go/v15 v15.0.2
go: added github.com/cpuguy83/go-md2man/v2 v2.0.7
go: added github.com/felixge/httpsnoop v1.0.4
go: added github.com/go-faster/city v1.0.1
go: added github.com/go-faster/errors v0.7.1
go: added github.com/go-logr/logr v1.4.3
go: added github.com/go-logr/stdr v1.2.2
go: added github.com/go-sql-driver/mysql v1.9.3
go: added github.com/goccy/go-json v0.10.5
go: added github.com/google/flatbuffers v25.2.10+incompatible
go: added github.com/google/s2a-go v0.1.9
go: added github.com/google/uuid v1.6.0
go: added github.com/googleapis/enterprise-certificate-proxy v0.3.6
go: added github.com/googleapis/gax-go/v2 v2.15.0
go: added github.com/jinzhu/inflection v1.0.0
go: added github.com/jinzhu/now v1.1.5
go: added github.com/joho/godotenv v1.5.1
go: added github.com/klauspost/compress v1.18.0
go: added github.com/klauspost/cpuid/v2 v2.3.0
go: added github.com/lib/pq v1.10.9
go: added github.com/mattn/go-sqlite3 v1.14.28
go: added github.com/paulmach/orb v0.11.1
go: added github.com/pierrec/lz4/v4 v4.1.22
go: added github.com/russross/blackfriday/v2 v2.1.0
go: added github.com/segmentio/asm v1.2.0
go: added github.com/shopspring/decimal v1.4.0
go: added github.com/sirupsen/logrus v1.9.3
go: added github.com/urfave/cli/v2 v2.27.7
go: added github.com/xrash/smetrics v0.0.0-20250705151800-55b8f293f342
go: added github.com/zeebo/xxh3 v1.0.2
go: added go.opentelemetry.io/auto/sdk v1.1.0
go: added go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.62.0
go: added go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.62.0
go: added go.opentelemetry.io/otel v1.37.0
go: added go.opentelemetry.io/otel/metric v1.37.0
go: added go.opentelemetry.io/otel/trace v1.37.0
go: added golang.org/x/crypto v0.40.0
go: added golang.org/x/exp v0.0.0-20250718183923-645b1fa84792
go: added golang.org/x/mod v0.26.0
go: added golang.org/x/net v0.42.0
go: added golang.org/x/oauth2 v0.30.0
go: added golang.org/x/sync v0.16.0
go: added golang.org/x/sys v0.34.0
go: added golang.org/x/text v0.27.0
go: added golang.org/x/time v0.12.0
go: added golang.org/x/tools v0.35.0
go: added golang.org/x/xerrors v0.0.0-20240903120638-7835f813f4da
go: added google.golang.org/api v0.243.0
go: added google.golang.org/genproto v0.0.0-20250721164621-a45f3dfb1074
go: added google.golang.org/genproto/googleapis/api v0.0.0-20250721164621-a45f3dfb1074
go: added google.golang.org/genproto/googleapis/rpc v0.0.0-20250721164621-a45f3dfb1074
go: added google.golang.org/grpc v1.74.2
go: added google.golang.org/protobuf v1.36.6
go: added gopkg.in/yaml.v3 v3.0.1
go: added gorm.io/driver/bigquery v1.2.0
go: added gorm.io/gorm v1.30.0
```

(exit code 0)

Closing.
